[tasks.win-build]
command = "cargo"
args = ["build", "--target", "x86_64-pc-windows-gnu"]

[tasks.win-run]
dependencies = ["win-build"]
command = "wine"
args = ["target/x86_64-pc-windows-gnu/debug/${CARGO_MAKE_PROJECT_NAME}.exe"]

[tasks.dev]
env = { "SIMCC_HOST" = "localhost:8080", "RETRY_MILLIS" = 200 }
command = "cargo"
args = ["run"]
