[tasks.win-build]
command = "cargo"
args = ["build", "--target", "x86_64-pc-windows-gnu", "--release"]

[tasks.win-run]
dependencies = ["win-build"]
command = "wine"
args = ["target/x86_64-pc-windows-gnu/debug/${CARGO_MAKE_PROJECT_NAME}.exe"]

[tasks.dev]
env = { "SIMCC_HOST" = "localhost:8080", "HTTP_COMMANDER_RECONNECT" = 400, "WS_COMMANDER_RECONNECT" = 1000 }
command = "cargo"
args = ["run"]
